name: flutter_benchmark
description: A new Flutter package project.
version: 1.0.1
homepage: https://github.com/mahulerachit/flutter_benchmark

environment:
  sdk: ">=2.15.0 <3.0.0"
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  plugin_platform_interface: ^2.0.2
  path_provider: ^2.0.10
  share_plus: ^4.0.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  plugin:
    platforms:
      android:
        package: com.rachit.flutter_benchmark
        pluginClass: FlutterBenchmarkPlugin
      ios:
        pluginClass: FlutterBenchmarkPlugin
      web:
        pluginClass: FlutterBenchmarkWeb
        fileName: src/platform/flutter_benchmark_web.dart
