name: flutter_benchmark
description: A new Flutter package project.
version: 1.5.0
homepage: https://github.com/mahulerachit/flutter_benchmark

environment:
  sdk: '>=3.2.1 <4.0.0'
  flutter: ">=2.5.0"

dependencies:
  flutter:
    sdk: flutter
  flutter_web_plugins:
    sdk: flutter
  path_provider: 2.1.1
  plugin_platform_interface: 2.1.7
  share_plus: 7.2.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: 3.0.1

flutter:
  plugin:
    platforms:
      android:
        package: com.rachit.flutter_benchmark
        pluginClass: FlutterBenchmarkPlugin
      ios:
        pluginClass: FlutterBenchmarkPlugin
      web:
        pluginClass: FlutterBenchmarkWeb
        fileName: src/platform/flutter_benchmark_web.dart
